import numpy as np

f1 = open('./ensemble/all/910_305.csv', 'r')
f2 = open('./ensemble/all/904_171.csv', 'r')
f3 = open('./ensemble/all/902_lcl.csv', 'r')
f4 = open('./ensemble/all/902_147.csv', 'r')
f5 = open('./ensemble/all/5.csv', 'r')
f6 = open('./ensemble/all/6.csv', 'r')
f7 = open('./ensemble/all/7.csv', 'r')
f8 = open('./ensemble/all/8.csv', 'r')
f9 = open('./ensemble/all/9.csv', 'r')
f10 = open('./ensemble/all/10.csv', 'r')
f11 = open('./ensemble/all/11.csv', 'r')
f12 = open('./ensemble/all/12.csv', 'r')
f13 = open('./ensemble/all/13.csv', 'r')
f14 = open('./ensemble/all/14.csv', 'r')
f15 = open('FINAL_14_1.csv', 'w')
f1.readline()
f2.readline()
f3.readline()
f4.readline()
f5.readline()
f6.readline()
f7.readline()
f8.readline()
f9.readline()
f10.readline()
f11.readline()
f12.readline()
f13.readline()
f14.readline()
f15.write('driver_trip,prob\n')

for line in f1:
    line = line.split(',')
    a=float(line[1])
    b=float(f2.readline().split(',')[1])
    c=float(f3.readline().split(',')[1])
    d=float(f4.readline().split(',')[1])
    e=float(f5.readline().split(',')[1])
    f=float(f6.readline().split(',')[1])
    g=float(f7.readline().split(',')[1])
    h=float(f8.readline().split(',')[1])
    i=float(f9.readline().split(',')[1])
    j=float(f10.readline().split(',')[1])
    k=float(f11.readline().split(',')[1])
    l=float(f12.readline().split(',')[1])
    m=float(f13.readline().split(',')[1])
    n=float(f14.readline().split(',')[1])
    f15.write(line[0] + ',' + str((a+b+c+d+e+f+g+h+i+j+k+l+m+n)/14.0) + '\n')
f1.close()
f2.close()
f3.close()
f4.close()
f5.close()
f6.close()
f7.close()
f8.close()
f9.close()
f10.close()
f11.close()
f12.close()
f13.close()
f14.close()
f15.close()
